#pragma once

#define SHADER_BATCH_KEY_NR_POINT_LIGHTS "NR_POINT_LIGHTS"
#define SHADER_BATCH_KEY_NR_SPOT_LIGHTS "NR_SPOT_LIGHTS"
#define SHADER_BATCH_KEY_HAS_SHADOWS "HAS_SHADOWS"
#define SHADER_BATCH_KEY_HAS_POINT_SHADOWS "HAS_POINT_SHADOWS"
#define SHADER_BATCH_KEY_PROJECT "PROJECT"

#define SHADER_REFRAC_KEY_DYNAMIC_OPACITY "DYNAMIC_OPACITY"

#define SHADER_PDEPTH_KEY_NR_POINT_LIGHTS "NR_POINT_LIGHTS"

#define SHADER_VAL_ON "1"
#define SHADER_VAL_OFF "0"